export const URLS = {
  HOME: '/',
  EXPLORE: '/explore',
  GALLERY: '/gallery',
  SOLUTIONS: '/solutions',
  ABOUT: '/about',
  MEDIA: '/media-center',
  BLOG: '/blog',
  CONTACT: '/contact',
  FAQ: '/faq',
  GREENFLEET: '/solutions/green-fleet',
  FLEET360: '/solutions/corporate-ev-fleet',
  EVCARE: '/solutions/ev-care',
  ASSEMBLI: '/solutions/assemli',
  METROCHARGE: '/solutions/metro-charge',
  RYDE: '/solutions/ryde',
};
