export const URLS = {
  HOME: '/',
  EXPLORE: '/explore',
  GALLERY: '/gallery',
  SERVICES: '/services',
  ABOUT: '/about',
  MEDIA: '/media-center',
  BLOG: '/blog',
  CONTACT: '/contact',
  FAQ: '/faq',
  GREENFLEET: '/services/green-fleet',
  FLEET360: '/services/corporate-ev-fleet',
  EVCARE: '/services/ev-care',
  ASSEMBLI: '/services/assemli',
  METROCHARGE: '/services/metro-charge',
  RYDE: '/services/ryde',
};
