import type { vehicle } from '~/types/types';
export const vehicles: vehicle[] = [
  {
    name: 'E-Bus',
    description:
      'The Metro Electric Mass Transit E-Bus is a state-of-the-art electric vehicle designed to redefine sustainable urban transportation. Equipped with a robust 160 kWh battery, it boasts an impressive range of 265 km per charge, making it ideal for city-wide transit systems. Engineered for efficiency and eco-friendliness, the Metro Electric offers smooth, quiet rides while significantly reducing carbon emissions. This advanced mass transit solution combines innovation, reliability, and environmental consciousness to meet the growing demands for sustainable public transportation. Perfect for modern urban settings, it exemplifies the future of green mobility.',
    category: 'bus',
    price: '₦310,000,000',
    images: ['/vehicles/Bus1.png', '/vehicles/Bus2.jpg', '/vehicles/Bus3.png'],
    specification: [
      { label: 'NAME', value: 'Metro Electric' },
      { label: 'MODEL', value: 'Mass Transit' },
      { label: 'BATTERY SIZE', value: '160kwh' },
      { label: 'RANGE', value: '265 km' },
      { label: 'COLOR', value: 'WHITE' },
    ],
    features: [
      'Eco-Friendly Powertrain',
      'Spacious & Passenger Focused Design',
      'Smart Technology Integration',
      'Quick Charging Capability',
      'Impressive Range',
      'Energy Efficiency',
      'Safety Features',
      'Durability and Reliability',
    ],
  },
  {
    name: 'Hongqi E-QM5',
    description:
      'The Hongqi E-QM5 is a 4-door, 5-seat all-electric sedan built for efficient city and executive mobility. With LFP battery options, a smooth front-wheel-drive setup, practical cabin technology, and reliable safety features, it offers a refined electric driving experience for everyday transportation.',
    category: 'car',
    price: '₦55,000,000',
    images: [
      '/vehicles/hongqi1.png',
      '/vehicles/hongqi2.png',
      '/vehicles/hongqi3.png',
      '/vehicles/hongqi4.png',
      '/vehicles/hongqi5.jpeg',
    ],
    specification: [
      { label: 'VEHICLE TYPE', value: '4-Door 5-Seat All-Electric Sedan' },
      { label: 'DIMENSIONS (L X W X H)', value: '4,657 x 1,814 x 1,490 mm' },
      { label: 'WHEELBASE', value: '2,680 mm' },
      { label: 'CURB WEIGHT (EST.)', value: '~1,645 - 1,750 kg' },
      { label: 'COLOR', value: 'WHITE/BLACK' },
      { label: 'SEATING CAPACITY', value: '5 Seats' },
      { label: 'DRIVE TYPE', value: 'Front-Wheel Drive (FWD)' },
      { label: 'BATTERY TYPE', value: 'Lithium Iron Phosphate (LFP)' },
      {
        label: 'BATTERY CAPACITY',
        value: '54.0 kWh (Standard) / 61.9 kWh (Long Range)',
      },
      {
        label: 'RANGE',
        value: '420 km  / 560 km CLTC',
      },
      { label: 'MOTOR POWER', value: '120 kW (Max)' },
      { label: 'MOTOR TORQUE', value: '250 Nm (Max)' },
      { label: 'TOP SPEED', value: '140 km/h' },
      { label: '0 - 100 KM/H', value: '~11.8 s' },
      {
        label: 'ENERGY CONSUMPTION',
        value: '~11.9 - 12.8 kWh/100 km (CLTC)',
      },
      { label: 'CHARGING TIME (AC)', value: '6.5 h (6.6 kW)' },
      { label: 'CHARGING TIME (DC)', value: '30 min (30% - 80%)' },
      { label: 'SUSPENSION (FRONT / REAR)', value: 'MacPherson / Multi-link' },
      { label: 'BRAKES (FRONT / REAR)', value: 'Ventilated Disc / Disc' },
      { label: 'TIRE SIZE', value: '195/60 R16' },
      { label: 'INFOTAINMENT SCREEN', value: '10.25-inch Touchscreen' },
      { label: 'INSTRUMENT CLUSTER', value: '7-inch LCD' },
      { label: 'SOUND SYSTEM', value: '6-speaker Audio System' },
      {
        label: 'ADAS SYSTEM',
        value: 'Basic Driver Assistance System (ABS, ESC, TPMS, Parking Sensors)',
      },
      {
        label: 'SAFETY FEATURES',
        value: '4 Airbags, ABS, EBD, ESC, HHC, ISOFIX, Rear Parking Sensors, TPMS',
      },
    ],
    features: [
      'Efficient LFP Battery Technology',
      'Long Range Battery Options',
      'Front-Wheel Drive Comfort',
      'Fast DC Charging',
      'Touchscreen Infotainment',
      'Driver Assistance Features',
      '5-Seat Sedan Layout',
      'Comprehensive Safety Systems',
    ],
  },
  {
    name: 'Xiaomi SU7',
    description:
      'The Xiaomi SU7 is a 2024 full-size four-door fastback electric sedan from Xiaomi Auto. Launched in Beijing in March 2024, it combines a low-drag body, strong single- and dual-motor powertrain options, long CLTC driving range, fast charging on the Max variant, and Xiaomi HyperOS smart ecosystem integration.',
    category: 'car',
    price: '₦75,000,000',
    images: [
      '/vehicles/xiaomi_su7_1.png',
      '/vehicles/xiaomi_su7_2.png',
      '/vehicles/xiaomi_su7_3.png',
      '/vehicles/xiaomi_su7_4.jpg',
      '/vehicles/xiaomi_su7_5.jpg',
    ],
    specification: [
      {
        label: 'VEHICLE TYPE',
        value: 'Full-Size 4-Door Fastback Electric Sedan',
      },
      { label: 'MODEL YEAR', value: '2024' },
      { label: 'LAUNCH', value: 'March 2024, Beijing' },
      {
        label: 'DIMENSIONS (L X W X H)',
        value: '4,997 x 1,963 x 1,440 - 1,455 mm',
      },
      { label: 'COLOR', value: 'WHITE' },
      { label: 'WHEELBASE', value: '3,000 mm' },
      { label: 'SEATING CAPACITY', value: '5 Seats' },
      {
        label: 'DRIVE TYPE',
        value: 'Rear-Wheel Drive (Standard/Pro) / All-Wheel Drive (Max)',
      },
      { label: 'DRAG COEFFICIENT', value: '0.195 Cd' },
      {
        label: 'BATTERY CAPACITY',
        value: '73.6 kWh (Standard) / 94.3 kWh (Pro) / 101 kWh CATL Qilin (Max)',
      },
      {
        label: 'RANGE',
        value: '700 km / 800 km CLTC',
      },
      { label: 'CHARGING ARCHITECTURE', value: '800V (Max)' },
      { label: 'FAST CHARGING', value: 'Up to 510 km range in 15 min (Max)' },
      {
        label: 'MOTOR POWER',
        value: '220 kW (Standard/Pro) / 495 kW AWD (Max)',
      },
      {
        label: 'MOTOR TORQUE',
        value: '400 Nm (Standard) / 438 Nm (Pro) / 838 Nm (Max)',
      },
      { label: 'TOP SPEED', value: '210 km/h (Standard) / 265 km/h (Max)' },
      {
        label: '0 - 100 KM/H',
        value: '5.28 s (Standard) / 4.68 s (Pro) / 2.78 s (Max)',
      },
      {
        label: 'INFOTAINMENT SCREEN',
        value: '16.1-inch 3K Central Touchscreen',
      },
      {
        label: 'INSTRUMENT CLUSTER',
        value: 'Rotating Instrument Cluster Display',
      },
      { label: 'OPERATING SYSTEM', value: 'Xiaomi HyperOS' },
      {
        label: 'CONNECTIVITY',
        value:
          'Xiaomi smartphone and smart home integration, CarPlay, UWB proximity unlocking, iPad rear-seat controls',
      },
      {
        label: 'ADAS SYSTEM',
        value: 'L2+ Assisted Driving with LiDAR and high-precision sensors',
      },
      {
        label: 'DRIVER ASSISTANCE',
        value: 'Adaptive Cruise Control, Lane-Keeping Assist, Automatic Emergency Braking',
      },
      {
        label: 'PREMIUM EQUIPMENT',
        value:
          'Active rear spoiler, adjustable ride height, air suspension, soft-close automatic doors, HUD, active noise cancellation',
      },
      {
        label: 'INTERIOR',
        value:
          'Artificial leather dashboard, leather front bucket seats, aluminium-finish center console',
      },
      { label: 'STORAGE', value: 'Front trunk plus rear boot' },
    ],
    features: [
      'Ultra-Low 0.195 Cd Drag Coefficient',
      'Standard, Pro, and Max Powertrain Options',
      'Up to 800 km CLTC Range',
      '800V Ultra-Fast Charging on Max Variant',
      'Xiaomi HyperOS Smart Ecosystem',
      'L2+ Assisted Driving with LiDAR',
      '16.1-inch 3K Central Touchscreen',
      'Active Rear Spoiler and Adjustable Ride Height',
    ],
  },
  {
    name: 'Leapmotor B01',
    description:
      'The Leapmotor B01 is a smart, efficient all-electric sedan designed for modern urban lifestyles. Combining practical range, intuitive technology, and everyday comfort, it offers an affordable entry into electric mobility for first-time EV owners and city professionals.',
    category: 'car',
    price: '₦41,000,000',
    images: [
      '/vehicles/leanmotors_b01_1.png',
      '/vehicles/leanmotors_b01_2.png',
      '/vehicles/leanmotors_b01_3.png',
    ],
    specification: [
      { label: 'VEHICLE TYPE', value: '4-Door 5-Seat All-Electric Sedan' },
      { label: 'DIMENSIONS (L X W X H)', value: '4,770 x 1,880 x 1,490 mm' },
      { label: 'WHEELBASE', value: '2,735 mm' },
      { label: 'CURB WEIGHT (EST.)', value: '~1,520 - 1,640 kg' },
      { label: 'SEATING CAPACITY', value: '5 Seats' },
      { label: 'DRIVE TYPE', value: 'Front-Wheel Drive (FWD)' },
      { label: 'BATTERY TYPE', value: 'Lithium Iron Phosphate (LFP)' },
      {
        label: 'BATTERY CAPACITY',
        value: '43.9 kWh (Standard) / 56.2 kWh (Long Range)',
      },
      {
        label: 'RANGE',
        value: 'Up to 430 km (Standard) / Up to 480 km (Long Range) CLTC',
      },
      {
        label: 'MOTOR POWER',
        value: '100 kW (Standard) / 120 - 130 kW (Long Range)',
      },
      {
        label: 'MOTOR TORQUE',
        value: '180 Nm (Standard) / 200 - 220 Nm (Long Range)',
      },
      { label: 'TOP SPEED', value: '160 km/h' },
      { label: '0 - 100 KM/H', value: '~9.0 s (Standard) / ~7.5 s (Long Range)' },
      {
        label: 'ENERGY CONSUMPTION',
        value: '~11.5 - 12.5 kWh/100 km (CLTC)',
      },
      { label: 'CHARGING TIME (AC)', value: '6.5 h (6.6 kW)' },
      { label: 'CHARGING TIME (DC)', value: '30 min (30% - 80%)' },
      { label: 'SUSPENSION (FRONT / REAR)', value: 'MacPherson / Torsion Beam' },
      { label: 'BRAKES (FRONT / REAR)', value: 'Ventilated Disc / Disc' },
      { label: 'TIRE SIZE', value: '215/50 R17' },
      { label: 'INFOTAINMENT SCREEN', value: '14.6-inch Touchscreen' },
      { label: 'INSTRUMENT CLUSTER', value: '8.8-inch LCD' },
      { label: 'SOUND SYSTEM', value: '6-speaker Audio System' },
      {
        label: 'ADAS SYSTEM',
        value: 'Basic Driver Assistance (ABS, ESC, TPMS, Parking Sensors)',
      },
      {
        label: 'SAFETY FEATURES',
        value: '4 Airbags, ABS, EBD, ESC, HHC, ISOFIX, Rear Parking Sensors, TPMS',
      },
      {
        label: 'EXTERIOR COLOURS',
        value: 'Pearl White, Glacier Grey, Starry Grey, Midnight Black',
      },
      {
        label: 'WARRANTY',
        value: '5 Years / 120,000 km (Vehicle) | 8 Years / 160,000 km (Battery)',
      },
    ],
    features: [
      'Affordable All-Electric Sedan',
      'Up to 480 km CLTC Range',
      'Efficient LFP Battery Options',
      'Front-Wheel Drive Simplicity',
      '14.6-inch Touchscreen',
      'Fast DC Charging',
      'Practical 5-Seat Cabin',
      'Core Safety and Driver Assistance Features',
    ],
  },
  {
    name: 'Leapmotor C16',
    description:
      'The Leapmotor C16 is a premium 6-seater all-electric SUV that combines spacious comfort, intelligent technology, and impressive range. Designed for modern families, it delivers strong performance, safety, and efficiency.',
    category: 'car',
    price: '₦66,000,000',
    images: [
      '/vehicles/leapmotor_c16_1.png',
      '/vehicles/leapmotor_c16_2.png',
      '/vehicles/leapmotor_c16_3.jpeg',
      '/vehicles/leapmotor_c16_4.png',
    ],
    specification: [
      { label: 'VEHICLE TYPE', value: '6-Seater All-Electric SUV (BEV / EREV)' },
      { label: 'DIMENSIONS (L X W X H)', value: '4,915 x 1,905 x 1,770 mm' },
      { label: 'WHEELBASE', value: '2,825 mm' },
      { label: 'CURB WEIGHT', value: '2,435 kg' },
      { label: 'SEATING CAPACITY', value: '6 Seats (2+2+2)' },
      { label: 'DRIVE TYPE', value: 'Rear-Wheel Drive / All-Wheel Drive' },
      { label: 'BATTERY TYPE', value: 'Lithium Iron Phosphate (LFP)' },
      {
        label: 'BATTERY CAPACITY',
        value: '67.7 kWh / 79.9 kWh (BEV) | ~42 kWh (EREV)',
      },
      { label: 'RANGE', value: '520 km / 580 km CLTC (BEV)' },
      { label: 'EREV PURE EV RANGE', value: '200 km (CLTC)' },
      { label: 'EREV TOTAL RANGE', value: '1,095 km combined' },
      { label: 'MOTOR POWER', value: '215 kW (RWD) / 400 kW (AWD)' },
      { label: 'MOTOR TORQUE', value: '360 Nm (RWD) / 720 Nm (AWD)' },
      { label: 'TOP SPEED', value: '190 km/h' },
      { label: '0 - 100 KM/H', value: '6.4 s (AWD)' },
      { label: 'ENERGY CONSUMPTION', value: '15.9 kWh/100 km' },
      { label: 'CHARGING TIME (AC)', value: '6.5 h (7 kW)' },
      { label: 'CHARGING TIME (DC)', value: '0.5 h (30% - 80%)' },
      { label: 'SUSPENSION (FRONT / REAR)', value: 'MacPherson / Multi-link' },
      { label: 'BRAKES (FRONT / REAR)', value: 'Ventilated Disc / Disc' },
      { label: 'TIRE SIZE', value: '255/45 R20' },
      {
        label: 'INFOTAINMENT SCREEN',
        value: '14.6-inch 2.5K Floating Touchscreen',
      },
      { label: 'INSTRUMENT CLUSTER', value: '10.25-inch Full LCD' },
      { label: 'COCKPIT CHIP', value: 'Qualcomm Snapdragon SA8295P' },
      { label: 'OPERATING SYSTEM', value: 'Leapmotor OS 4.0 Plus' },
      { label: 'VOICE AI', value: 'DeepSeek+ and Tongyi Qianwen dual AI' },
      { label: 'SOUND SYSTEM', value: '21-speaker Sony PSS with Dolby Atmos' },
      { label: 'REAR ENTERTAINMENT', value: '15.6-inch rear screen with cinema mode' },
      { label: 'REFRIGERATOR', value: 'Built-in 1.8L heating/cooling unit (top trim)' },
      {
        label: 'SEAT FEATURES',
        value: 'Heating, ventilation, 10-point massage (front and rear)',
      },
      { label: 'FLAT BED MODE', value: '1.8-metre wide flat sleeping surface' },
      {
        label: 'AIR QUALITY SYSTEM',
        value: 'AQS active air quality management + PM2.5 filter',
      },
      { label: 'ADAS SYSTEM', value: 'Leapmotor Pilot (L2+)' },
      { label: 'LIDAR', value: 'Yes - upper trim variants' },
      { label: 'ADAS FUNCTIONS', value: '27 functions including NAP, NAC, Highway and City Pilot' },
      { label: '360 CAMERA', value: 'Yes - with memory parking' },
      {
        label: 'SAFETY FEATURES',
        value: '6 Airbags, ESP, AEB, LDW, LKA, ACC, 360 Camera',
      },
      {
        label: 'BATTERY SAFETY',
        value: 'CTC2.0 submarine-grade thermoformed steel (2,000 MPa)',
      },
      { label: 'CRASH RATING', value: 'Top score - C-IASI safety test' },
      { label: 'BLOWOUT CONTROL', value: 'LMC straight-line stability after tyre burst' },
      {
        label: 'EXTERIOR COLOURS',
        value: 'Pearl White, Glacier Silver, Metallic Grey, Midnight Black, Tundra Green',
      },
      {
        label: 'WARRANTY',
        value: '5 Years / 120,000 km (Vehicle) | 8 Years / 160,000 km (Battery)',
      },
    ],
    features: [
      'Premium 6-Seat Family SUV',
      'BEV and EREV Powertrain Options',
      'Up to 580 km CLTC BEV Range',
      'Up to 1,095 km Combined EREV Range',
      'Leapmotor OS 4.0 Plus',
      '21-Speaker Sony Audio System',
      'L2+ Leapmotor Pilot Assistance',
      'Advanced Cabin Comfort Features',
    ],
  },
  {
    name: 'Leapmotor C10',
    description:
      'The Leapmotor C10 is a stylish, intelligent, and highly efficient all-electric SUV that delivers premium comfort, advanced technology, and impressive range for modern lifestyles.',
    category: 'car',
    price: '₦57,000,000',
    images: [
      '/vehicles/leapmotor_c10_1.png',
      '/vehicles/leapmotor_c10_2.png',
      '/vehicles/leapmotor_c10_3.png',
    ],
    specification: [
      { label: 'VEHICLE TYPE', value: '5-Seater All-Electric SUV' },
      { label: 'DIMENSIONS (L X W X H)', value: '4,739 x 1,900 x 1,680 mm' },
      { label: 'WHEELBASE', value: '2,825 mm' },
      { label: 'CURB WEIGHT (EST.)', value: '~1,850 - 2,050 kg (variant dependent)' },
      { label: 'SEATING CAPACITY', value: '5 Seats (2+3)' },
      { label: 'DRIVE TYPE', value: 'Rear-Wheel Drive / All-Wheel Drive' },
      { label: 'BATTERY TYPE', value: 'Lithium Iron Phosphate (LFP)' },
      {
        label: 'BATTERY CAPACITY',
        value: '69.9 kWh (Standard) / 69.9 kWh (Long Range)',
      },
      {
        label: 'RANGE',
        value: 'Up to 530 km (Standard) / Up to 605 km (Long Range) CLTC',
      },
      {
        label: 'MOTOR POWER',
        value: 'Single Motor RWD: ~170 kW / Dual Motor AWD: ~320 kW',
      },
      { label: 'MOTOR TORQUE', value: 'RWD: 320 Nm / AWD: 360 Nm combined' },
      { label: 'TOP SPEED', value: '170 km/h' },
      { label: '0 - 100 KM/H', value: '~7.5 s (RWD) / ~5.9 s (AWD)' },
      { label: 'ENERGY CONSUMPTION', value: '15.2 kWh/100 km (CLTC)' },
      { label: 'CHARGING TIME (AC)', value: '6.5 h (7 kW)' },
      { label: 'CHARGING TIME (DC)', value: '0.5 h (30% - 80%)' },
      { label: 'SUSPENSION (FRONT / REAR)', value: 'MacPherson / Multi-link' },
      { label: 'BRAKES (FRONT / REAR)', value: 'Ventilated Disc / Disc' },
      { label: 'TIRE SIZE', value: '235/50 R19' },
      { label: 'INFOTAINMENT SCREEN', value: '14.6-inch 2.5K' },
      { label: 'INSTRUMENT CLUSTER', value: '10.25-inch Full LCD' },
      { label: 'HEAD-UP DISPLAY (HUD)', value: 'Optional 10.25-inch' },
      { label: 'SOUND SYSTEM', value: '12-speaker with Dolby Atmos' },
      { label: 'PANORAMIC SUNROOF', value: 'Yes' },
      { label: 'ADAS SYSTEM', value: 'Leapmotor Pilot (L2+)' },
      {
        label: 'SAFETY FEATURES',
        value: '6 Airbags, ESP, AEB, LDW, LKA, ACC, 360 Camera, BSD',
      },
      {
        label: 'EXTERIOR COLOURS',
        value: 'Glacier White, Starry Silver, Metallic Grey, Midnight Black, Pine Green',
      },
      {
        label: 'WARRANTY',
        value: '5 Years / 120,000 km (Vehicle) | 8 Years / 160,000 km (Battery)',
      },
    ],
    features: [
      'Intelligent 5-Seat Electric SUV',
      'Up to 605 km CLTC Range',
      'RWD and AWD Options',
      '14.6-inch 2.5K Infotainment',
      '12-Speaker Dolby Atmos Audio',
      'L2+ Leapmotor Pilot Assistance',
      'Fast DC Charging',
      'Panoramic Sunroof',
    ],
  },
  {
    name: 'Wuling Starlight S (SUV)',
    description:
      'The Wuling Starlight S is a compact crossover SUV available in both pure electric and plug-in hybrid versions. Built on the SGMW Tianyu EV modular architecture, it offers generous cabin space, 985 mm of rear legroom, and strong value for family mobility.',
    category: 'car',
    price: '₦56,000,000',
    images: [
      '/vehicles/wuling_starlight _s_1.png',
      '/vehicles/wuling_starlight _s_2.png',
      '/vehicles/wuling_starlight _s_3.png',
      '/vehicles/wuling_starlight _s_4.png',
    ],
    specification: [
      { label: 'VEHICLE TYPE', value: '5-Seat Compact Crossover SUV (BEV / PHEV)' },
      { label: 'DIMENSIONS (L X W X H)', value: '4,745 x 1,890 x 1,680 mm' },
      { label: 'WHEELBASE', value: '2,800 mm' },
      { label: 'SEATING CAPACITY', value: '5 Seats' },
      { label: 'PLATFORM', value: 'SGMW Tianyu EV modular architecture' },
      { label: 'DRIVE TYPE', value: 'Front-Wheel Drive (FWD)' },
      { label: 'BATTERY TYPE (BEV)', value: 'Lithium Iron Phosphate (LFP)' },
      { label: 'BATTERY CAPACITY (BEV)', value: '60 kWh' },
      { label: 'RANGE', value: '510 km CLTC (BEV)' },
      { label: 'BATTERY CAPACITY (PHEV)', value: '20.5 kWh' },
      { label: 'PHEV PURE EV RANGE', value: '130 km' },
      { label: 'PHEV TOTAL RANGE', value: 'Over 1,100 km' },
      { label: 'MOTOR POWER', value: '150 kW (204 hp)' },
      { label: 'MOTOR TORQUE', value: '310 Nm' },
      { label: '0 - 100 KM/H', value: '7.7 s (BEV) / 7.9 s (PHEV)' },
      { label: 'TOP SPEED', value: '175 km/h' },
      { label: 'PHEV ENGINE', value: '1.5L Atkinson-cycle naturally aspirated' },
      { label: 'DC FAST CHARGING', value: 'Full charge in approximately 20 minutes' },
      { label: 'SUSPENSION (FRONT / REAR)', value: 'MacPherson / Torsion Beam' },
      { label: 'TIRE SIZE', value: '18-inch alloy wheels (standard)' },
      { label: 'INFOTAINMENT SCREEN', value: '15.6-inch Touchscreen' },
      { label: 'INSTRUMENT CLUSTER', value: '8.8-inch Digital Display' },
      { label: 'STEERING WHEEL', value: 'Leather-wrapped' },
      { label: 'REAR LEGROOM', value: '985 mm between rows' },
      { label: 'STORAGE COMPARTMENTS', value: '23 dedicated spaces throughout cabin' },
      { label: 'SEAT FEATURE', value: 'Flat-fold nap bed mode' },
      { label: 'RAIN SENSING WIPERS', value: 'Yes' },
      { label: 'ADAS LEVEL', value: 'L2' },
      { label: '360 CAMERA', value: 'Yes - high-resolution, standard on all variants' },
      {
        label: 'SAFETY FEATURES',
        value: 'Full airbag suite, AEB, ABS, Auto-hold, ACC, ESC',
      },
      { label: 'STARTING PRICE (CNY)', value: '~100,000 (~$14,000 USD)' },
      { label: 'WARRANTY', value: 'Available - per SGMW terms' },
    ],
    features: [
      'BEV and PHEV Family SUV Options',
      '510 km CLTC BEV Range',
      'Over 1,100 km PHEV Total Range',
      '15.6-inch Touchscreen',
      'Class-Leading Rear Legroom',
      '23 Cabin Storage Compartments',
      'L2 Driver Assistance',
      'Standard High-Resolution 360 Camera',
    ],
  },
  {
    name: 'Wuling Starlight (Sedan)',
    description:
      'The Wuling Starlight is a mid-size all-electric sedan from SAIC-GM-Wuling, built on the Tianyu D architecture. It offers a refined four-door cabin, efficient LFP battery options, a smooth front-wheel-drive setup, and practical everyday range for city and intercity driving.',
    category: 'car',
    price: '₦48,000,000',
    images: [
      '/vehicles/wuling_starlight_sedan_1.png',
      '/vehicles/wuling_starlight_sedan_2.png',
      '/vehicles/wuling_starlight_sedan_3.png',
    ],
    specification: [
      { label: 'VEHICLE TYPE', value: '4-Door 5-Seat Mid-Size Electric Sedan' },
      { label: 'DIMENSIONS (L X W X H)', value: '4,835 x 1,860 x 1,515 mm' },
      { label: 'WHEELBASE', value: '2,800 mm' },
      { label: 'CURB WEIGHT', value: '1,600 - 1,695 kg' },
      { label: 'SEATING CAPACITY', value: '5 Seats' },
      { label: 'PLATFORM', value: 'SGMW Tianyu D architecture' },
      { label: 'DRIVE TYPE', value: 'Front-Wheel Drive (FWD)' },
      { label: 'BATTERY TYPE', value: 'Lithium Iron Phosphate (LFP)' },
      {
        label: 'BATTERY CAPACITY',
        value: '41.9 kWh (Standard) / 54.3 kWh (Long Range) / 69.2 kWh (2025 Extended)',
      },
      {
        label: 'RANGE',
        value: '410 km / 510 km / up to 610 km CLTC',
      },
      { label: 'MOTOR TYPE', value: 'Permanent Magnet Synchronous' },
      { label: 'MOTOR POWER', value: '100 kW (134 hp)' },
      { label: 'TOP SPEED', value: '150 km/h' },
      { label: 'CHARGING TIME (AC)', value: '~6 - 8 h (11 kW)' },
      { label: 'CHARGING TIME (DC)', value: '30 min (30% - 80%)' },
      { label: 'BATTERY SUPPLIER', value: 'CATL' },
      { label: 'INFOTAINMENT SCREEN', value: 'Large Central Touchscreen' },
      { label: 'OPERATING SYSTEM', value: 'Ling OS' },
      { label: 'ADAS PLATFORM', value: 'Lingmou (Integrated)' },
      { label: 'COMPUTE', value: 'Horizon Robotics Journey' },
      { label: 'VOICE CONTROL', value: 'Supported' },
      { label: 'CABIN STORAGE', value: '33 L across 14 dedicated compartments' },
      { label: 'SUSPENSION', value: 'Coil Springs with Passive Damping' },
      { label: 'ROOF', value: 'Metal' },
      {
        label: 'SAFETY FEATURES',
        value: 'Airbag Suite, ABS, EBD, ESC, TPMS, Parking Sensors',
      },
      { label: 'WARRANTY', value: 'Available - per SGMW terms' },
    ],
    features: [
      'Mid-Size All-Electric Sedan',
      'Up to 610 km CLTC Range',
      'Efficient LFP Battery Options',
      'CATL Battery Supply',
      'Smooth Front-Wheel Drive',
      'Large Central Touchscreen with Ling OS',
      'Integrated Lingmou ADAS',
      'Spacious Cabin with 14 Storage Compartments',
    ],
  },

  // {
  //   name: '7KW Level 2 Charging Station',
  //   description:
  //     'The 7KW Level 2 AC Charging Station is ideal for homes, offices, hotels, apartments, and locations where vehicles remain parked for several hours. It offers a reliable and affordable charging solution for daily EV users.',
  //   category: 'charger',
  //   price: 'Contact for price',
  //   images: [
  //     'https://example.com/chargers/7kw-level-2-charger-1.jpg',
  //     'https://example.com/chargers/7kw-level-2-charger-2.jpg',
  //     'https://example.com/chargers/7kw-level-2-charger-3.jpg',
  //   ],
  //   specification: [
  //     { label: 'CHARGER TYPE', value: 'Level 2 AC Charging Station' },
  //     { label: 'POWER OUTPUT', value: '7 kW' },
  //     { label: 'CHARGING SPEED', value: 'Standard' },
  //     { label: 'CURRENT TYPE', value: 'AC' },
  //     {
  //       label: 'SMALL EV CHARGING TIME',
  //       value: '4 - 6 hours for 30 - 40 kWh batteries',
  //     },
  //     {
  //       label: 'MEDIUM EV CHARGING TIME',
  //       value: '7 - 9 hours for 50 - 60 kWh batteries',
  //     },
  //     {
  //       label: 'LARGE EV CHARGING TIME',
  //       value: '10 - 12+ hours for 70+ kWh batteries',
  //     },
  //     {
  //       label: 'BEST FOR',
  //       value:
  //         'Homeowners, workplaces, hotels, residential estates, and small commercial facilities',
  //     },
  //     { label: 'TYPICAL USE CASE', value: 'Home / Office' },
  //     { label: 'ESTIMATED TIME', value: '4 - 12 hrs' },
  //   ],
  //   features: [
  //     'Perfect for Overnight Charging',
  //     'Lower Installation Cost',
  //     'Compact and Easy to Deploy',
  //     'Ideal for Private Users and Staff Parking Lots',
  //   ],
  // },
  // {
  //   name: '22KW AC Charging Station',
  //   description:
  //     'The 22KW AC Charging Station is a faster commercial AC charging solution designed for public places and businesses needing shorter charging turnaround times.',
  //   category: 'charger',
  //   price: 'Contact for price',
  //   images: [
  //     'https://example.com/chargers/22kw-ac-charger-1.jpg',
  //     'https://example.com/chargers/22kw-ac-charger-2.jpg',
  //     'https://example.com/chargers/22kw-ac-charger-3.jpg',
  //   ],
  //   specification: [
  //     { label: 'CHARGER TYPE', value: 'AC Charging Station' },
  //     { label: 'POWER OUTPUT', value: '22 kW' },
  //     { label: 'CHARGING SPEED', value: 'Fast AC' },
  //     { label: 'CURRENT TYPE', value: 'AC' },
  //     {
  //       label: 'SMALL EV CHARGING TIME',
  //       value: '1.5 - 2.5 hours for 30 - 40 kWh batteries',
  //     },
  //     {
  //       label: 'MEDIUM EV CHARGING TIME',
  //       value: '3 - 4 hours for 50 - 60 kWh batteries',
  //     },
  //     {
  //       label: 'LARGE EV CHARGING TIME',
  //       value: '4 - 6 hours for 70+ kWh batteries',
  //     },
  //     {
  //       label: 'BEST FOR',
  //       value:
  //         'Shopping malls, offices, restaurants, hotels, hospitals, universities, and public car parks',
  //     },
  //     { label: 'TYPICAL USE CASE', value: 'Public / Commercial' },
  //     { label: 'ESTIMATED TIME', value: '1.5 - 6 hrs' },
  //   ],
  //   features: [
  //     'Three Times Faster than 7KW Charging',
  //     'Suitable for Commercial Environments',
  //     'Supports Destination Charging',
  //     'Ideal for Short to Medium Parking Durations',
  //   ],
  // },
  // {
  //   name: '40KW DC Fast Charging Station',
  //   description:
  //     'The 40KW DC Fast Charger provides direct current charging, bypassing the vehicle onboard charger for significantly faster charging speeds.',
  //   category: 'charger',
  //   price: 'Contact for price',
  //   images: [
  //     'https://example.com/chargers/40kw-dc-fast-charger-1.jpg',
  //     'https://example.com/chargers/40kw-dc-fast-charger-2.jpg',
  //     'https://example.com/chargers/40kw-dc-fast-charger-3.jpg',
  //   ],
  //   specification: [
  //     { label: 'CHARGER TYPE', value: 'DC Fast Charging Station' },
  //     { label: 'POWER OUTPUT', value: '40 kW' },
  //     { label: 'CHARGING SPEED', value: 'Fast DC' },
  //     { label: 'CURRENT TYPE', value: 'DC' },
  //     { label: 'CHARGING RANGE', value: '20% - 80%' },
  //     { label: 'SMALL EV CHARGING TIME', value: '30 - 40 minutes' },
  //     { label: 'MEDIUM EV CHARGING TIME', value: '45 - 60 minutes' },
  //     { label: 'LARGE EV CHARGING TIME', value: '60 - 90 minutes' },
  //     {
  //       label: 'BEST FOR',
  //       value: 'Fleet depots, fuel stations, business centers, taxi parks, and transit locations',
  //     },
  //     { label: 'TYPICAL USE CASE', value: 'Fleet / Public' },
  //     { label: 'ESTIMATED TIME', value: '30 - 90 mins' },
  //   ],
  //   features: [
  //     'Fast Turnaround for Fleet and Commercial Use',
  //     'Efficient Public Charging Option',
  //     'Suitable for Medium Traffic Charging Hubs',
  //     'Reduces Downtime for EV Drivers',
  //   ],
  // },
  // {
  //   name: '60KW DC Fast Charging Station',
  //   description:
  //     'The 60KW DC Fast Charger is a premium fast-charging solution designed for busy charging stations and commercial fleets needing rapid charging.',
  //   category: 'charger',
  //   price: 'Contact for price',
  //   images: [
  //     'https://example.com/chargers/60kw-dc-fast-charger-1.jpg',
  //     'https://example.com/chargers/60kw-dc-fast-charger-2.jpg',
  //     'https://example.com/chargers/60kw-dc-fast-charger-3.jpg',
  //   ],
  //   specification: [
  //     { label: 'CHARGER TYPE', value: 'DC Fast Charging Station' },
  //     { label: 'POWER OUTPUT', value: '60 kW' },
  //     { label: 'CHARGING SPEED', value: 'Faster DC' },
  //     { label: 'CURRENT TYPE', value: 'DC' },
  //     { label: 'CHARGING RANGE', value: '20% - 80%' },
  //     { label: 'SMALL EV CHARGING TIME', value: '20 - 30 minutes' },
  //     { label: 'MEDIUM EV CHARGING TIME', value: '30 - 45 minutes' },
  //     { label: 'LARGE EV CHARGING TIME', value: '45 - 60 minutes' },
  //     {
  //       label: 'BEST FOR',
  //       value:
  //         'Fuel stations, public charging hubs, logistics fleets, ride-hailing fleets, and transport terminals',
  //     },
  //     { label: 'TYPICAL USE CASE', value: 'High Traffic Sites' },
  //     { label: 'ESTIMATED TIME', value: '20 - 60 mins' },
  //   ],
  //   features: [
  //     'Faster Charging than 40KW Systems',
  //     'High User Turnover',
  //     'Excellent for Commercial and Public Networks',
  //     'Reliable for Continuous Operation',
  //   ],
  // },
  // {
  //   name: '160KW DC Fast Charging Station',
  //   description:
  //     'The 160KW Ultra-Fast DC Charger is a high-performance charging solution built for next-generation EVs and heavy-duty commercial operations.',
  //   category: 'charger',
  //   price: 'Contact for price',
  //   images: [
  //     'https://example.com/chargers/160kw-dc-fast-charger-1.jpg',
  //     'https://example.com/chargers/160kw-dc-fast-charger-2.jpg',
  //     'https://example.com/chargers/160kw-dc-fast-charger-3.jpg',
  //   ],
  //   specification: [
  //     { label: 'CHARGER TYPE', value: 'Ultra-Fast DC Charging Station' },
  //     { label: 'POWER OUTPUT', value: '160 kW' },
  //     { label: 'CHARGING SPEED', value: 'Ultra Fast DC' },
  //     { label: 'CURRENT TYPE', value: 'DC' },
  //     { label: 'CHARGING RANGE', value: '20% - 80%' },
  //     { label: 'SMALL EV CHARGING TIME', value: '10 - 15 minutes' },
  //     { label: 'MEDIUM EV CHARGING TIME', value: '15 - 25 minutes' },
  //     { label: 'LARGE EV CHARGING TIME', value: '25 - 40 minutes' },
  //     {
  //       label: 'BEST FOR',
  //       value:
  //         'Highways, intercity routes, premium charging hubs, bus depots, logistics centers, and large commercial fleets',
  //     },
  //     { label: 'TYPICAL USE CASE', value: 'Highway / Premium Fleet' },
  //     { label: 'ESTIMATED TIME', value: '10 - 40 mins' },
  //     {
  //       label: 'CHARGING DURATION NOTE',
  //       value:
  //         'Actual time depends on vehicle battery capacity, state of charge, vehicle maximum charging acceptance rate, battery temperature, charger efficiency, and power supply conditions',
  //     },
  //   ],
  //   features: [
  //     'Ultra-Fast Charging Speeds',
  //     'Minimizes Waiting Time',
  //     'Ideal for Highways and Premium Charging Networks',
  //     'Supports Modern EVs with High Charging Acceptance Rates',
  //   ],
  // },
];
